### ISSUE TITLE
w5500 & ESP module

### ISSUE THREAD

**Issue by mkeyno** [cnlohr/espthernet#2]
hi @cnlohr and thanks for sharing this elegant job , however I'm using ready to use module for both Ethernet and ESP , I was wondering if you have any solution for that , also I've used the Iggor Arduino ESP8266 core lib's , and any  interested to make ino sketch so could easily compile and uploaded by Arduino IDE

**Comment by cnlohr** [comment]
This is specifically for when you want to talk Ethernet with your ESP, not another device, too.  About the Arduino... I have tried several times to get Arduino working on the ESP and it's never worked out, so I've completely abandoned it.  My code is written to be as portable as I can make so it should port easily, but I'm not going to be the one to port it :-/

**Comment by mkeyno** [comment]
can you tell me when and with which version , because new version of this core very stable and they [embedded Ethernet library ](https://github.com/esp8266/Arduino/commit/2a01c2a)and its stable   , however not for w5500 yet, I hope you could try again , I'm watching your repo for any change

**Comment by cnlohr** [comment]
I don't understand your question.  This repo is for using the ESP as the Ethernet chip (Ethernet + Wifi).  That library looks like it does exactly what you want?

**Comment by mkeyno** [comment]
what I find from your note is, you've designed specific hardware and handle special connection(I2S) with a Ethernet chip , please correct me if I mistaken,  I was wondering why don't you choose ready to use Ethernet module and connect with ESP module through SPI connection and just run sketch form IDE to dispatch package from Ethernet stack to ESP stack?

**Comment by cnlohr** [comment]
No.  There is no ethernet chip.  You can literally wire the ethernet wires into the ESP (Though that would be a shoddy way of doing it).  The ESP acts as the PHY, MAC and Interface.   No modules, no nothing.
