### ISSUE TITLE
ESP SDK

### ISSUE THREAD

**Issue by markingle** [cnlohr/espthernet#3]
Does it matter where I pull the esp sdk?

I have been fighting my GNU gcc install this evening but I think I have it fixed.

**Comment by cnlohr** [comment]
I strongly suggest using the ESP NON OS SDK that is referenced in the project.  As far as the rest of it, I usually use esp open sdk.

**Comment by markingle** [comment]
I cannot get the code to compile on my Mac.  The make file is looking for a file in sep-open-sdk

/bin/sh: /Users/MarkIngle/esp-open-sdk/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc: No such file or directory

Xcode is on my Mac too and I thing its causing a problem with the compile.....

**Comment by markingle** [comment]
Could you provide a link to the ESP open sdk you are using as referred to in your make file?

**Comment by markingle** [comment]
Well I have conquered the compile demons on my Mac and burned the firmware on to the ESP.  Where did you get the line driver and manchester chip from?

**Comment by cnlohr** [comment]
I /think/ I was using the ISL3177

**Comment by markingle** [comment]
Thanks!  I found a Bel fuse S558-5999-R3 magnetics chip on a old 3Com net card....should be perfect for the job!

**Comment by cnlohr** [comment]
Oh you meant the magnetics!
