### ISSUE TITLE
Hello! I have a problem executing the command: 

### ISSUE THREAD

**Issue by kasimusNo** [cnlohr/espthernet#8]
when executing a command: Make ---> Makefile:74: recipe execution error for the target «image.elf.bin» (Ubuntu 16.04 x32, Python 2.7.12, Nodemcu esp8266)

**Comment by kasimusNo** [comment]
$ ~/q/esp-open-sdk/examples/espthernet$ make
~/esp-open-sdk/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc -mlongcalls -I ~/esp-open-sdk/esp_iot_sdk_v1.5.2/include -Imyclib -Iinclude -Iuser -Os -I ~/esp-open-sdk/esp_iot_sdk_v1.5.2/include/ -Icommon -DICACHE_FLASH -Ietherhelp	-Wl,--gc-sections -flto driver/uart.c common/http.c common/mystuff.c common/flash_rewriter.c common/commonservices.c common/http_custom.c common/mdns.c common/mfs.c user/custom_commands.c user/i2sduplex.c user/user_main.c user/manchestrate.c etherhelp/net_compat.c etherhelp/crc32.c etherhelp/tcp.c etherhelp/iparpetc.c  -nostdlib -L~/esp-open-sdk/esp_iot_sdk_v1.5.2/lib -L~/esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.2/libgcc.a -g ~/esp-open-sdk/esp_iot_sdk_v1.5.2/lib/libmain.a ~/esp-open-sdk/esp_iot_sdk_v1.5.2/lib/libpp.a ~/esp-open-sdk/esp_iot_sdk_v1.5.2/lib/libnet80211.a ~/esp-open-sdk/esp_iot_sdk_v1.5.2/lib/libwpa.a ~/esp-open-sdk/esp_iot_sdk_v1.5.2/lib/liblwip.a ~/esp-open-sdk/esp_iot_sdk_v1.5.2/lib/libssl.a ~/esp-open-sdk/esp_iot_sdk_v1.5.2/lib/libupgrade.a ~/esp-open-sdk/esp_iot_sdk_v1.5.2/lib/libnet80211.a ~/esp-open-sdk/esp_iot_sdk_v1.5.2/lib/liblwip.a ~/esp-open-sdk/esp_iot_sdk_v1.5.2/lib/libphy.a ~/esp-open-sdk/esp_iot_sdk_v1.5.2/lib/libcrypto.a ~/esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.2/libgcc.a -T ~/esp-open-sdk/esp_iot_sdk_v1.5.2/ld/eagle.app.v6.ld -B ~/esp-open-sdk/esp_iot_sdk_v1.5.2/lib -o image.elf.bin
/bin/sh: 1: /home/sd/esp-open-sdk/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc: not found
Makefile:74: recipe execution error for the target «image.elf.bin»
make: *** [image.elf.bin] Error 127

**Comment by kasimusNo** [comment]
I just started to study this area! namely, work with nodemcu esp8266 and wanted to upload espthernet to this device (https://github.com/cnlohr/espthernet) installed esp-open-sdk according to instructions (https://github.com/pfalcon/esp-open-sdk)! there is no problem with the blink example! and with this, this error pops up during compilation!

**Comment by kasimusNo** [comment]
and if I upload a sketch: esptool.py --baud 57600 write_flash 0x00000 image.elf-0x00000.bin 0x40000 image.elf-0x40000.bin! 
Connect to esp via wifi! (esp_31FF12)
---> I'm going ---> http://192.168.4.1 there is an inscription on the page: "File not found"

I’m doing something wrong or not completing it?

**Comment by kasimusNo** [comment]
https://github.com/cnlohr/espusb/issues/40

**Comment by kasimusNo** [comment]
the question remains with compilation! :(

**Comment by cnlohr** [comment]
hmm... a few things.

(1) You need to install the pfalcon SDK.  see https://github.com/cnlohr/esp82xx
(2) You must flash the mpfs file to the appropriate location for the build of what you're doing.  In the case of espthernet, you need to flash it to 0x10000.  You can build the mpfs file in the `web` folder

**Comment by kasimusNo** [comment]
(1) I will consider, I will try!
(2) solved the issue by reading the post https://github.com/cnlohr/espusb/issues/40 ( esptool.py -b 115200 --port /dev/ttyUSB0 write_flash 65536 web/page.mpfs)

**Comment by kasimusNo** [comment]
https://github.com/cnlohr/espthernet/blob/gh-pages/hardware/esp12e-ethernet.pdf 100% luck!?
https://github.com/cnlohr/espthernet/blob/gh-pages/hardware/nodemcu-ethernet.png 30-40% of success!?

**Comment by cnlohr** [comment]
Indeed!  Realistically, if you're willing to put in time, experiment and do more with an oscilloscope it can in practice become very reliable.  But it's not "good"
